# Generated by Django 2.0 on 2017-12-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date saved')),
                ('url', models.URLField()),
                ('url_title', models.CharField(max_length=255)),
                ('url_text', models.TextField()),
                ('url_preview', models.CharField(max_length=255)),
            ],
        ),
    ]
