# Generated by Django 2.0 on 2017-12-15 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='url_preview',
            new_name='short_text',
        ),
        migrations.RenameField(
            model_name='bookmarks',
            old_name='url_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='bookmarks',
            old_name='url_title',
            new_name='title',
        ),
    ]
