# Generated by Django 2.0 on 2017-12-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171215_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookMarks',
            new_name='BookMark',
        ),
    ]
