# Generated by Django 2.0 on 2018-01-08 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180103_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='site_name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
