# Generated by Django 2.0 on 2018-01-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_bookmark_site_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMarkForTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date saved')),
                ('url', models.URLField()),
                ('site_name', models.TextField(default='', max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='None', max_length=500)),
                ('image', models.URLField(default='')),
            ],
        ),
    ]
