# Generated by Django 2.0 on 2018-01-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180113_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField()),
                ('positions', models.TextField(default='', max_length=500)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BookMark')),
            ],
        ),
    ]
