# Generated by Django 2.0 on 2018-01-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_wordanalytics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordAnalytics',
            new_name='Word_Analytics',
        ),
    ]
