# Generated by Django 2.0 on 2018-01-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180118_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_analytics',
            name='positions',
        ),
        migrations.RemoveField(
            model_name='word_analytics',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='word_analytics',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='word_analytics',
            name='word',
            field=models.CharField(default='', max_length=255),
        ),
    ]
