# Generated by Django 2.0 on 2018-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180118_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
