# Generated by Django 2.0 on 2018-02-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English',
            new_name='Translate',
        ),
    ]
